import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
//https://www.conordewey.com/

import { Noto_Sans_Mono } from "next/font/google";

const notoSansMono = Noto_Sans_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto-sans-mono",
});

export const metadata = {
  title: "Teemu Hämäläinen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSansMono.variable} w-1/3 h-screen flex flex-col justify-between mx-auto`}
      >
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
