import "./globals.css";
import Navbar from "./components/Navbar";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Teemu Hämäläinen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"w-1/3 h-screen justify-center items-center mx-auto"}>
        <main className={roboto.className}>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
