import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import { Roboto_Mono } from "next/font/google";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Teemu Hämäläinen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} lg:w-2/5 h-screen flex flex-col justify-between mx-auto`}
      >
        <Navbar />
        <main className="flex-1 p-2 lg:p-0">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
